# Generated by Django 3.2 on 2021-04-12 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbums',
            name='album_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
